// POC ingest: GitHub Docs is public markdown with real product screenshots whose
// alt text describes what is on screen, which is exactly what a planner needs to
// pick the right shot. Downloads images locally so the page's own CSP serves them.
import { mkdir, writeFile } from "node:fs/promises";

const RAW = "https://raw.githubusercontent.com/github/docs/main";
const ROOT = new URL("../../", import.meta.url);
const IMAGE_DIR = new URL("public/poc-docs/", ROOT);

const ARTICLES = [
  "content/repositories/creating-and-managing-repositories/quickstart-for-repositories.md",
  "content/pull-requests/how-tos/create-pull-requests/creating-a-pull-request.md",
  "content/get-started/using-github/hello-world.md",
  "content/issues/tracking-your-work-with-issues/using-issues/creating-an-issue.md",
  "content/pull-requests/how-tos/review-pull-requests/reviewing-proposed-changes-in-a-pull-request.md",
];

const frontmatter = (source) => {
  const match = /^---\n(.*?)\n---\n/s.exec(source);
  if (!match) return { fields: {}, body: source };
  const fields = {};
  for (const line of match[1].split("\n")) {
    const field = /^(title|shortTitle|intro):\s*(.*)$/.exec(line);
    if (field) fields[field[1]] = field[2].replace(/^['"]|['"]$/g, "");
  }
  return { fields, body: source.slice(match[0].length) };
};

// Liquid conditionals and data references are authoring machinery, not prose.
const prose = (line) => line
  .replace(/\{%.*?%\}/g, "")
  .replace(/\{\{\s*[^}]*?\}\}/g, "")
  .replace(/\[([^\]]+)\]\([^)]*\)/g, "$1")
  .replace(/[*_`>#]/g, "")
  .replace(/\s+/g, " ")
  .trim();

function blocks(body) {
  const out = [];
  for (const rawLine of body.split("\n")) {
    const image = /!\[([^\]]*)\]\(([^)\s]+)/.exec(rawLine);
    if (image) {
      const path = image[2];
      if (/\.(png|jpe?g|webp|gif)$/i.test(path)) {
        out.push({ type: "image", alt: image[1].replace(/\s+/g, " ").trim(), path });
      }
      continue;
    }
    const heading = /^(#{2,4})\s+(.*)$/.exec(rawLine);
    if (heading) {
      const text = prose(heading[2]);
      if (text) out.push({ type: "heading", text });
      continue;
    }
    const step = /^\s*(?:\d+\.|[-*])\s+(.*)$/.exec(rawLine);
    const text = prose(step ? step[1] : rawLine);
    if (text.length > 2) out.push({ type: step ? "step" : "text", text });
  }
  return out;
}

async function download(path, name) {
  for (const base of [ "https://docs.github.com", RAW ]) {
    const response = await fetch(`${base}${path}`);
    if (!response.ok) continue;
    await writeFile(new URL(name, IMAGE_DIR), Buffer.from(await response.arrayBuffer()));
    return `/poc-docs/${name}`;
  }
  return null;
}

await mkdir(IMAGE_DIR, { recursive: true });
const articles = [];
let downloaded = 0;
for (const article of ARTICLES) {
  const response = await fetch(`${RAW}/${article}`);
  if (!response.ok) { console.error(`skip ${article}: ${response.status}`); continue; }
  const { fields, body } = frontmatter(await response.text());
  const parsed = blocks(body);
  for (const block of parsed) {
    if (block.type !== "image") continue;
    const name = block.path.split("/").slice(-2).join("-");
    block.url = await download(block.path, name);
    if (block.url) downloaded += 1;
    delete block.path;
  }
  const kept = parsed.filter((block) => block.type !== "image" || block.url);
  articles.push({
    slug: article.split("/").pop().replace(/\.md$/, ""),
    title: fields.title ?? article,
    intro: prose(fields.intro ?? ""),
    blocks: kept,
  });
  console.log(`${fields.title} — ${kept.length} blocks, ${kept.filter((b) => b.type === "image").length} screenshots`);
}

const module = `// Generated by scripts/poc/fetch-docs.mjs. Do not edit.\nexport const pocDocs = ${JSON.stringify({ product: "GitHub", articles }, null, 2)};\n`;
await writeFile(new URL("functions/_video-chat/poc-docs-data.mjs", ROOT), module);
console.log(`\n${downloaded} screenshots in public/poc-docs/, data in functions/_video-chat/poc-docs-data.mjs`);
