/**
 * Generated by scripts/generate-builtin-catalog.ts.
 * Do not edit by hand; run `npm run catalog:sync`.
 */
import type { PlayerTemplateData } from "./player-kit.js";

export const GENERATED_BUILTIN_PLAYER_TEMPLATES = [
  {
    "id": "cinemaMedia",
    "defaults": {
      "mediaUrl": "",
      "mediaType": "video",
      "mediaPoster": ""
    },
    "usesGlobalTransition": false
  },
  {
    "id": "chapterTitle",
    "defaults": {
      "title": "A different perspective"
    },
    "usesGlobalTransition": false
  },
  {
    "id": "editorialTimeline",
    "defaults": {
      "events": [
        {
          "label": "Observe"
        },
        {
          "label": "Understand"
        },
        {
          "label": "Act"
        }
      ],
      "mediaUrl": "",
      "mediaType": "video",
      "mediaPoster": ""
    },
    "usesGlobalTransition": false
  },
  {
    "id": "mobileMessage",
    "defaults": {
      "mediaUrl": "",
      "mediaType": "video",
      "mediaPoster": "",
      "message": "Can we talk?",
      "app": "Messages"
    },
    "usesGlobalTransition": false
  },
  {
    "id": "comparison",
    "defaults": {
      "leftText": "More distractions",
      "rightText": "More room to think",
      "mediaUrl": "",
      "mediaType": "video",
      "mediaPoster": ""
    },
    "usesGlobalTransition": false
  },
  {
    "id": "quote",
    "defaults": {
      "mediaUrl": "",
      "mediaType": "video",
      "mediaPoster": ""
    },
    "usesGlobalTransition": false
  },
  {
    "id": "keyFigure",
    "defaults": {
      "mediaUrl": "",
      "mediaType": "video",
      "mediaPoster": ""
    },
    "usesGlobalTransition": false
  }
] as const satisfies readonly PlayerTemplateData[];

export const GENERATED_BUILTIN_VIDEO_BACKDROP_IDS: readonly string[] = ["cinemaMedia","editorialTimeline","mobileMessage","comparison","quote","keyFigure"];
