/**
 * Generated by scripts/generate-builtin-catalog.ts.
 * Do not edit by hand; run `npm run catalog:sync`.
 */
import type { PlayerTemplateData } from "./player-kit.js";

export const GENERATED_BUILTIN_PLAYER_TEMPLATES = [
  {
    "id": "cinemaMedia",
    "defaults": {
      "mediaUrl": "",
      "mediaType": "video",
      "mediaPoster": ""
    },
    "usesGlobalTransition": false
  },
  {
    "id": "chapterTitle",
    "defaults": {
      "title": "A different perspective"
    },
    "usesGlobalTransition": false
  },
  {
    "id": "focusCards",
    "defaults": {
      "items": [
        "Listen closely",
        "Notice the pattern",
        "Make room for change"
      ]
    },
    "usesGlobalTransition": false
  },
  {
    "id": "editorialTimeline",
    "defaults": {
      "events": [
        {
          "label": "Observe"
        },
        {
          "label": "Understand"
        },
        {
          "label": "Act"
        }
      ]
    },
    "usesGlobalTransition": false
  },
  {
    "id": "mobileMessage",
    "defaults": {
      "mediaUrl": "",
      "mediaType": "video",
      "mediaPoster": "",
      "message": "Can we talk?",
      "app": "Messages"
    },
    "usesGlobalTransition": false
  },
  {
    "id": "comparison",
    "defaults": {
      "leftText": "More distractions",
      "rightText": "More room to think"
    },
    "usesGlobalTransition": false
  },
  {
    "id": "quote",
    "defaults": {},
    "usesGlobalTransition": false
  },
  {
    "id": "keyFigure",
    "defaults": {},
    "usesGlobalTransition": false
  }
] as const satisfies readonly PlayerTemplateData[];

export const GENERATED_BUILTIN_VIDEO_BACKDROP_IDS: readonly string[] = ["cinemaMedia","mobileMessage"];
