/**
 * Generated by scripts/generate-builtin-catalog.ts.
 * Do not edit by hand; run `npm run catalog:sync`.
 */
import type { ComponentType } from "react";
import type { SceneTemplateProps } from "./types.js";

export type BuiltinTemplateModule = { default: ComponentType<SceneTemplateProps> };

export const GENERATED_BUILTIN_TEMPLATE_LOADERS = {
  "cinemaMedia": () => import("../scene-templates/cinema-media.js").then((module) => ({ default: module.MediaSceneTemplate })),
  "chapterTitle": () => import("../scene-templates/chapter-title.js").then((module) => ({ default: module.TitleSceneTemplate })),
  "focusCards": () => import("../scene-templates/focus-cards.js").then((module) => ({ default: module.CardsSceneTemplate })),
  "editorialTimeline": () => import("../scene-templates/editorial-timeline.js").then((module) => ({ default: module.TimelineSceneTemplate })),
  "mobileMessage": () => import("../scene-templates/mobile-message.js").then((module) => ({ default: module.NotificationSceneTemplate })),
  "comparison": () => import("../scene-templates/comparison.js").then((module) => ({ default: module.ComparisonSceneTemplate })),
  "quote": () => import("../scene-templates/quote.js").then((module) => ({ default: module.QuoteSceneTemplate })),
  "keyFigure": () => import("../scene-templates/key-figure.js").then((module) => ({ default: module.KeyFigureSceneTemplate })),
} satisfies Record<string, () => Promise<BuiltinTemplateModule>>;
