/**
 * Generated by scripts/generate-builtin-catalog.ts.
 * Do not edit by hand; run `npm run catalog:sync`.
 */
import type { SceneTemplateMetadata } from "./catalog-types.js";

export const GENERATED_BUILTIN_TEMPLATE_CATALOG = [
  {
    "label": "Full-bleed",
    "description": "Immersive photo or video without a headline.",
    "usesGlobalTextEffect": false,
    "usesGlobalTransition": false,
    "usesGlobalBackgroundEffect": false,
    "textCanvas": "tight",
    "id": "cinemaMedia",
    "family": "Media & motion",
    "jobs": [
      "setup",
      "atmosphere",
      "payoff"
    ],
    "register": "motion-led",
    "useWhen": "Show a relevant place, activity or subject. The asset is resolved separately from a shot description. ",
    "avoidWhen": "No relevant asset can be resolved or the scene needs structured explanation.",
    "minDuration": 3,
    "preferredDuration": 6,
    "timing": {
      "contentFields": [],
      "contentUnit": "words",
      "revealSeconds": 0,
      "holdSeconds": 3,
      "exitSeconds": 0
    },
    "schema": {
      "type": "object",
      "properties": {
        "mediaKeyword": {
          "type": "string",
          "format": "stock-media-keyword",
          "minLength": 1,
          "maxLength": 80,
          "description": "2–8 word literal subject/action search intent, max80characters. Host resolves URLs.",
          "examples": [
            "Ocean waves breaking on a rocky shore"
          ]
        },
        "mediaUrl": {
          "type": "string",
          "format": "uri",
          "description": "Host-only approved photo or video URL.",
          "default": ""
        },
        "mediaType": {
          "type": "string",
          "enum": [
            "photo",
            "video"
          ],
          "default": "video",
          "description": "Host-resolved asset kind."
        },
        "mediaPoster": {
          "type": "string",
          "format": "uri",
          "description": "Host-only approved poster URL for video decoding.",
          "default": ""
        },
        "mediaSource": {
          "type": "string",
          "enum": [
            "generate",
            "stock"
          ],
          "description": "Generate distinctive illustrative shots; use approved stock for familiar observable subjects."
        },
        "fallbackText": {
          "type": "string",
          "maxLength": 65,
          "description": "Optional grounded concise chapter text if this shot cannot be resolved; not visible over footage."
        }
      },
      "required": [],
      "additionalProperties": false,
      "x-vanillasky": {
        "allowsStockMedia": true,
        "requiredAnyOf": [
          [
            "mediaKeyword",
            "mediaUrl"
          ]
        ]
      }
    }
  },
  {
    "label": "Chapter",
    "description": "Centered white typography fades in, holds, and fades out on black.",
    "usesGlobalTextEffect": false,
    "usesGlobalTransition": false,
    "usesGlobalBackgroundEffect": false,
    "textCanvas": "tight",
    "id": "chapterTitle",
    "family": "Explainers",
    "jobs": [
      "setup",
      "payoff"
    ],
    "register": "motion-led",
    "useWhen": "An opening, new chapter or deliberate short takeaway needs its own visual beat. ",
    "avoidWhen": "A headline would merely repeat subtitles over an ordinary footage scene.",
    "minDuration": 3,
    "preferredDuration": 4,
    "timing": {
      "contentFields": [
        "title"
      ],
      "contentUnit": "words",
      "revealSeconds": 0.8,
      "holdSeconds": 1.5,
      "exitSeconds": 0.8
    },
    "schema": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string",
          "maxLength": 65,
          "description": "Short title. Line breaks optional.",
          "default": "A different perspective"
        }
      },
      "required": [
        "title"
      ],
      "additionalProperties": false
    }
  },
  {
    "label": "Focus cards",
    "description": "Two to four short phrases fade in sequentially on black; no boxes or heading.",
    "usesGlobalTextEffect": false,
    "usesGlobalTransition": false,
    "usesGlobalBackgroundEffect": false,
    "textCanvas": "tight",
    "id": "focusCards",
    "family": "Explainers",
    "jobs": [
      "setup",
      "proof"
    ],
    "register": "card-led",
    "useWhen": "Two to four short parallel points support an explanation. ",
    "avoidWhen": "The points require an order, long paragraphs, numerical data or additional images to make sense.",
    "minDuration": 4,
    "preferredDuration": 5,
    "timing": {
      "contentFields": [
        "items"
      ],
      "contentUnit": "items",
      "revealSeconds": 2.4,
      "holdSeconds": 1.8,
      "exitSeconds": 0
    },
    "schema": {
      "type": "object",
      "properties": {
        "items": {
          "type": "array",
          "minItems": 2,
          "maxItems": 4,
          "items": {
            "type": "string",
            "minLength": 1,
            "maxLength": 55
          },
          "default": [
            "Listen closely",
            "Notice the pattern",
            "Make room for change"
          ],
          "description": "2–4 parallel phrases, about2–6words each; no heading or numbering."
        }
      },
      "required": [
        "items"
      ],
      "additionalProperties": false
    }
  },
  {
    "label": "Timeline",
    "description": "Three to five events on a fine continuous line on black; without dates.",
    "usesGlobalTextEffect": false,
    "usesGlobalTransition": false,
    "usesGlobalBackgroundEffect": false,
    "textCanvas": "tight",
    "id": "editorialTimeline",
    "family": "Explainers",
    "jobs": [
      "setup",
      "proof"
    ],
    "register": "card-led",
    "useWhen": "Events unfold in an order, or actions form a process. No dates or heading. ",
    "avoidWhen": "The points are unordered or the story needs branching relationships.",
    "minDuration": 5,
    "preferredDuration": 6,
    "timing": {
      "contentFields": [
        "events"
      ],
      "contentUnit": "items",
      "revealSeconds": 3.2,
      "holdSeconds": 1.8,
      "exitSeconds": 0
    },
    "schema": {
      "type": "object",
      "properties": {
        "events": {
          "type": "array",
          "minItems": 3,
          "maxItems": 5,
          "items": {
            "type": "object",
            "properties": {
              "label": {
                "type": "string",
                "minLength": 1,
                "maxLength": 45
              }
            },
            "required": [
              "label"
            ],
            "additionalProperties": false
          },
          "default": [
            {
              "label": "Observe"
            },
            {
              "label": "Understand"
            },
            {
              "label": "Act"
            }
          ],
          "description": "3–5 ordered events or actions, each with one shortlabel; no dates."
        }
      },
      "required": [
        "events"
      ],
      "additionalProperties": false
    }
  },
  {
    "label": "Reach out",
    "description": "A frosted glass message over resolved media, without sender or timestamp.",
    "usesGlobalTextEffect": false,
    "usesGlobalTransition": false,
    "usesGlobalBackgroundEffect": false,
    "textCanvas": "tight",
    "id": "mobileMessage",
    "family": "Social & messaging",
    "jobs": [
      "setup"
    ],
    "register": "card-led",
    "useWhen": "A person or organization reaches out with a short message, alert or invitation. Message must be supplied or explicitly illustrative.",
    "avoidWhen": "The scene is a generic fact, a long exchange, or a message that would fabricate evidence.",
    "minDuration": 4,
    "preferredDuration": 6,
    "timing": {
      "contentFields": [
        "message",
        "app"
      ],
      "contentUnit": "words",
      "revealSeconds": 1,
      "holdSeconds": 2.2,
      "exitSeconds": 0
    },
    "schema": {
      "type": "object",
      "properties": {
        "mediaKeyword": {
          "type": "string",
          "format": "stock-media-keyword",
          "minLength": 1,
          "maxLength": 80,
          "description": "2–8 word literal subject/action search intent, max80characters. Host resolves URLs.",
          "examples": [
            "Ocean waves breaking on a rocky shore"
          ]
        },
        "mediaUrl": {
          "type": "string",
          "format": "uri",
          "description": "Host-only approved photo or video URL.",
          "default": ""
        },
        "mediaType": {
          "type": "string",
          "enum": [
            "photo",
            "video"
          ],
          "default": "video",
          "description": "Host-resolved asset kind."
        },
        "mediaPoster": {
          "type": "string",
          "format": "uri",
          "description": "Host-only approved poster URL for video decoding.",
          "default": ""
        },
        "message": {
          "type": "string",
          "maxLength": 120,
          "default": "Can we talk?",
          "description": "Exact supplied or explicitly illustrative message, preferably6–16words."
        },
        "app": {
          "type": "string",
          "maxLength": 24,
          "default": "Messages",
          "description": "Optional app label; Messages is the visualdefault."
        },
        "mediaSource": {
          "type": "string",
          "enum": [
            "generate",
            "stock"
          ],
          "description": "Generate distinctive illustrative shots; use approved stock for familiar observable subjects."
        }
      },
      "required": [
        "message"
      ],
      "additionalProperties": false,
      "x-vanillasky": {
        "allowsStockMedia": true,
        "requiredAnyOf": [
          [
            "mediaKeyword",
            "mediaUrl"
          ]
        ]
      }
    }
  },
  {
    "label": "Comparison",
    "description": "Two short statements with equal weight on black, side by side or stacked in portrait.",
    "usesGlobalTextEffect": false,
    "usesGlobalTransition": false,
    "usesGlobalBackgroundEffect": false,
    "textCanvas": "tight",
    "id": "comparison",
    "family": "Explainers",
    "jobs": [
      "proof"
    ],
    "register": "motion-led",
    "useWhen": "Explain a before/after change or two alternatives with short parallel statements. ",
    "avoidWhen": "There are more than two alternatives or a numerical chart is needed.",
    "minDuration": 4,
    "preferredDuration": 6,
    "timing": {
      "contentFields": [
        "leftText",
        "rightText",
        "leftLabel",
        "rightLabel"
      ],
      "contentUnit": "words",
      "revealSeconds": 1.2,
      "holdSeconds": 2.5,
      "exitSeconds": 0
    },
    "schema": {
      "type": "object",
      "properties": {
        "leftLabel": {
          "type": "string",
          "maxLength": 20,
          "description": "Optional shortidentifier for the first alternative."
        },
        "rightLabel": {
          "type": "string",
          "maxLength": 20,
          "description": "Optional shortidentifier for the second alternative."
        },
        "leftText": {
          "type": "string",
          "minLength": 1,
          "maxLength": 60,
          "default": "More distractions",
          "description": "First real alternative in one shortphrase."
        },
        "rightText": {
          "type": "string",
          "minLength": 1,
          "maxLength": 60,
          "default": "More room to think",
          "description": "Second real alternative, parallel to the first."
        }
      },
      "required": [
        "leftText",
        "rightText"
      ],
      "additionalProperties": false
    }
  },
  {
    "label": "Quote",
    "description": "A short exact quotation with a legible attribution on black.",
    "usesGlobalTextEffect": false,
    "usesGlobalTransition": false,
    "usesGlobalBackgroundEffect": false,
    "textCanvas": "tight",
    "id": "quote",
    "family": "Explainers",
    "jobs": [
      "proof"
    ],
    "register": "motion-led",
    "useWhen": "A supplied quotation deserves its own moment. Use exact source words and attribution only.",
    "avoidWhen": "No exact quotation or reliable attribution is supplied; never invent testimony.",
    "minDuration": 5,
    "preferredDuration": 7,
    "timing": {
      "contentFields": [
        "quote",
        "attribution"
      ],
      "contentUnit": "words",
      "revealSeconds": 1.2,
      "holdSeconds": 3,
      "exitSeconds": 0
    },
    "schema": {
      "type": "object",
      "properties": {
        "quote": {
          "type": "string",
          "minLength": 1,
          "maxLength": 140,
          "format": "grounded-quote",
          "examples": [
            "Look closely. There is always more to see."
          ],
          "description": "Exact supplied quotation; do not paraphrase or invent."
        },
        "attribution": {
          "type": "string",
          "minLength": 1,
          "maxLength": 60,
          "examples": [
            "Illustrative example"
          ],
          "description": "Grounded attribution belonging to these exact quotedwords."
        }
      },
      "required": [
        "quote",
        "attribution"
      ],
      "additionalProperties": false
    }
  },
  {
    "label": "Key figure",
    "description": "One supplied figure with one short label on black.",
    "usesGlobalTextEffect": false,
    "usesGlobalTransition": false,
    "usesGlobalBackgroundEffect": false,
    "textCanvas": "tight",
    "id": "keyFigure",
    "family": "Explainers",
    "jobs": [
      "proof"
    ],
    "register": "motion-led",
    "useWhen": "One verified quantity or supplied target anchors the explanation. Value, unit and context must match supplied evidence.",
    "avoidWhen": "No reliable figure is supplied or multiple values require a chart.",
    "minDuration": 4,
    "preferredDuration": 5,
    "timing": {
      "contentFields": [
        "value",
        "label"
      ],
      "contentUnit": "words",
      "revealSeconds": 0.8,
      "holdSeconds": 2.5,
      "exitSeconds": 0
    },
    "schema": {
      "type": "object",
      "properties": {
        "value": {
          "type": "string",
          "minLength": 1,
          "maxLength": 14,
          "format": "grounded-stat",
          "examples": [
            "42%"
          ],
          "description": "One supplied supported quantity, preserving its unit."
        },
        "label": {
          "type": "string",
          "minLength": 1,
          "maxLength": 50,
          "examples": [
            "Illustrative example"
          ],
          "description": "Exactly one shortlabel identifying the quantity and its context."
        }
      },
      "required": [
        "value",
        "label"
      ],
      "additionalProperties": false,
      "x-vanillasky": {
        "requiresStat": true
      }
    }
  }
] as const satisfies readonly SceneTemplateMetadata[];
