#!/usr/bin/env tsx

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  BUILTIN_TEMPLATE_MANIFEST,
  type BuiltinTemplateId,
} from "../src/visual-system/catalog/builtin-manifest.js";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const templatesDirectory = join(root, "src/visual-system/scene-templates");
const outputPath = join(root, "src/visual-system/catalog/catalog.generated.ts");
const loadersOutputPath = join(root, "src/visual-system/catalog/builtin-loaders.generated.ts");
const playerOutputPath = join(root, "src/visual-system/catalog/builtin-player.generated.ts");

const templateModules = {
  "cinemaMedia": {
    "file": "cinema-media.tsx",
    "component": "MediaSceneTemplate"
  },
  "chapterTitle": {
    "file": "chapter-title.tsx",
    "component": "TitleSceneTemplate"
  },
  "focusCards": {
    "file": "focus-cards.tsx",
    "component": "CardsSceneTemplate"
  },
  "editorialTimeline": {
    "file": "editorial-timeline.tsx",
    "component": "TimelineSceneTemplate"
  },
  "mobileMessage": {
    "file": "mobile-message.tsx",
    "component": "NotificationSceneTemplate"
  },
  "comparison": {
    "file": "comparison.tsx",
    "component": "ComparisonSceneTemplate"
  },
  "quote": {
    "file": "quote.tsx",
    "component": "QuoteSceneTemplate"
  },
  "keyFigure": {
    "file": "key-figure.tsx",
    "component": "KeyFigureSceneTemplate"
  }
} satisfies Record<BuiltinTemplateId, { file: string; component: string }>;

function renderGeneratedCatalog(): string {
  const catalog = BUILTIN_TEMPLATE_MANIFEST;
  const catalogIds = catalog.map(({ id }) => id).sort();
  const mappedIds = Object.keys(templateModules).sort();
  if (JSON.stringify(catalogIds) !== JSON.stringify(mappedIds)) {
    throw new Error("Built-in template source map does not match the compiled catalog");
  }
  for (const { file } of Object.values(templateModules)) {
    readFileSync(join(templatesDirectory, file), "utf8");
  }

  return `/**
 * Generated by scripts/generate-builtin-catalog.ts.
 * Do not edit by hand; run \`npm run catalog:sync\`.
 */
import type { SceneTemplateMetadata } from "./catalog-types.js";

export const GENERATED_BUILTIN_TEMPLATE_CATALOG = ${JSON.stringify(catalog, null, 2)} as const satisfies readonly SceneTemplateMetadata[];
`;
}

function renderGeneratedLoaders(): string {
  const entries = Object.entries(templateModules).map(([id, { file, component }]) => {
    const modulePath = `../scene-templates/${file.replace(/\.tsx$/, ".js")}`;
    return `  ${JSON.stringify(id)}: () => import(${JSON.stringify(modulePath)}).then((module) => ({ default: module.${component} })),`;
  });
  return `/**
 * Generated by scripts/generate-builtin-catalog.ts.
 * Do not edit by hand; run \`npm run catalog:sync\`.
 */
import type { ComponentType } from "react";
import type { SceneTemplateProps } from "./types.js";

export type BuiltinTemplateModule = { default: ComponentType<SceneTemplateProps> };

export const GENERATED_BUILTIN_TEMPLATE_LOADERS = {
${entries.join("\n")}
} satisfies Record<string, () => Promise<BuiltinTemplateModule>>;
`;
}

function renderGeneratedPlayerTemplates(): string {
  const templates = BUILTIN_TEMPLATE_MANIFEST.map((template) => ({
    id: template.id,
    defaults: Object.fromEntries(
      Object.entries(template.schema.properties).flatMap(([name, property]) =>
        property.default === undefined ? [] : [[name, property.default]],
      ),
    ),
    usesGlobalTransition: template.usesGlobalTransition,
    ...(template.transitionTiming ? { transitionTiming: template.transitionTiming } : {}),
  }));
  return `/**
 * Generated by scripts/generate-builtin-catalog.ts.
 * Do not edit by hand; run \`npm run catalog:sync\`.
 */
import type { PlayerTemplateData } from "./player-kit.js";

export const GENERATED_BUILTIN_PLAYER_TEMPLATES = ${JSON.stringify(templates, null, 2)} as const satisfies readonly PlayerTemplateData[];
`;
}

const generated = renderGeneratedCatalog();
const generatedLoaders = renderGeneratedLoaders();
const generatedPlayerTemplates = renderGeneratedPlayerTemplates();
if (process.argv.includes("--check")) {
  const current = readFileSync(outputPath, "utf8");
  const currentLoaders = readFileSync(loadersOutputPath, "utf8");
  const currentPlayerTemplates = readFileSync(playerOutputPath, "utf8");
  if (current !== generated || currentLoaders !== generatedLoaders || currentPlayerTemplates !== generatedPlayerTemplates) {
    throw new Error("Built-in catalog drifted; run npm run catalog:sync");
  }
} else {
  writeFileSync(outputPath, generated);
  writeFileSync(loadersOutputPath, generatedLoaders);
  writeFileSync(playerOutputPath, generatedPlayerTemplates);
}
